### ISSUE TITLE
Push to Nuvola Player project

### ISSUE THREAD

**Issue by thenyeguy** [tiliado/nuvola-app-kexp#1]

**Comment by fenryxo** [comment]
Hi @thenyeguy,Thanks for your work. I will probably take a look at it in February after I release Nuvola Player 3 beta.

**Comment by fenryxo** [comment]
Code look great. Some minor notes follow.

1. The letters KEXP in the icon could be white. It might look better. Also, [increase the icon size in Makefile to 128](https://groups.google.com/d/msg/nuvola-player-devel/a-axnC05sf8/a8hEsBolxiIJ) `ICON_SIZE ?= 128`.

2. If you want to maintain your integration script as a part of the Nuvola Player project, your repository will be transferred under Tiliado organization account (`tiliado/nuvola-app-kexp`) and you will have commit access to the repository. In that case, please change URL for bug reporting in `README.md`.

**Comment by thenyeguy** [comment]
Thanks for the comments!

1. I actually did those exact icon changes at the same time as the Spotify icon.

2. Transferring the repo to Tiliado sounds great. Is this just something I need to do under the repo settings?

**Comment by fenryxo** [comment]
Hello @thenyeguy 

> I actually did those exact icon changes at the same time as the Spotify icon.

Mea culpa, it seems I didn't update my local clone.

> Transferring the repo to Tiliado sounds great. Is this just something I need to do under the repo settings?

There is a GitHub documentation about [how to transfer repository from user to an organization](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization). You should now have sufficient rights to transfer the repository under [Tiliado Nuvola KEXP team](https://github.com/orgs/tiliado/teams/nuvola-kexp/repositories). Ping me when you are done and I'll create Debian/Ubuntu/Fedora packages ;-)

**Comment by thenyeguy** [comment]
Hi @fenryxo,

I have transferred the repository. Thanks for the help!

**Comment by fenryxo** [comment]
Packages are ready :-)
