### ISSUE TITLE
 ReferenceError: Can't find variable: flowplayer

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvola-app-kexp#5]
Hi,

diorite-4.11.0-1.fc28.x86_64
nuvolaruntime-4.11.0-1.fc28.x86_64
nuvola-app-kexp-1.2-4.fc28.noarch

when running nuvoal-app-kexp i get the following error message:
[martin@f28 SPECS]$ nuvolaruntime -D -a /usr/share/nuvolaruntime/web_apps/kexp/

> Runner: [WARNING Δ111859us DioriteGtk] Application.vala:82: Integration error. Failed to inject JavaScript API. Function 'Nuvola.core.emit' failed. file:///usr/share/nuvolaruntime/web_apps/kexp/integrate.js:75: ReferenceError: Can't find variable: flowplayer
> Gtk-Message: 12:22:37.326: GtkDialog mapped without a transient parent. This is discouraged.
> Runner: [DEBUG Δ02s687308us DioriteGlib] DuplexChannel.vala:551: Channel (2) has been closed.
> Runner: [DEBUG Δ000311us DioriteGlib] DuplexChannel.vala:338: The channel has already been closed

[nuvola-app-kexp-error.txt](https://github.com/tiliado/nuvola-app-kexp/files/2047876/nuvola-app-kexp-error.txt)

what is the reason ?

**Comment by fenryxo** [comment]
It is possible that the KEXP website has changed and the script needs to be updated.

@thenyeguy, could you look at it?

**Comment by fenryxo** [comment]
Fixed in release 1.3.
